ALTER TABLE user
ADD COLUMN created_at TIMESTAMP;

ALTER TABLE user
ADD COLUMN modified_at TIMESTAMP;

ALTER TABLE user
ADD COLUMN created_by VARCHAR(32);

ALTER TABLE user
ADD COLUMN modified_by VARCHAR(32);